name: deploy webapp to S3

on: 
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3

   - name: configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
      aws-region: ${{secrets.AWS_REGION}}
      
   - name: deploy to S3
     run: aws s3 sync . s3://${{secrets.S3_BUCKET_NAME}} --delete
 
